### ISSUE TITLE
White screen when trying to edit post after import

### ISSUE THREAD

**Issue by grandeljay** [WordPress/wordpress-importer#125]
In reference to https://github.com/wpeventmanager/wp-event-manager/issues/951 I am getting a white screen when trying to edit posts after importing them on PHP 8

```log
PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
PHP Deprecated:  allowed_block_types is <strong>deprecated</strong> since version 5.8.0! Use allowed_block_types_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
PHP Deprecated:  block_editor_settings is <strong>deprecated</strong> since version 5.8.0! Use block_editor_settings_all instead. in /html/wordpress/wp-includes/functions.php on line 5691
```

**Comment by dd32** [comment]
Hi @grandeljay,

I apologise for the delay in response here.

The deprecated notices here aren't indicative of an issue with the importer plugin, and is likely related to another plugin installed on the site.

Additionally, the errors mentioned in https://github.com/wpeventmanager/wp-event-manager/issues/951 related to `libxml_disable_entity_loader()` were fixed in b4b11945c5735868671b060b65ebd8978b15e9c4 which is 100% unrelated to the issue at hand.

I'm closing this issue as It doesn't appear to be importer related.
