### ISSUE TITLE
Fails to import files when their server gzips 

### ISSUE THREAD

**Issue by jakeparis** [WordPress/wordpress-importer#47]
When the importer attempts to get a media file which is getting sent from the server with compression (i.e. gzipped), the Content-Length header doesn't actually match the result of `filesize()`. In these cases, the code which runs that filesize comparison returns a false, and the file fails to import. 

There should be some kind of check for whether the file is getting sent with compression on and the conditional security take this into account.

**Comment by MrLeif** [comment]
Just had the same problem.
Found a solution here


Found my solution after a little more digging.

The problem lies in wordpress-importer

Found this from jan 30 on github:

https://github.com/WordPress/wordpress-importer/issues/47?_pjax=%23js-repo-pjax-container

Then later the solution here:

https://www.playnicetogether.com/2015/11/07/wordpress-importer-plugin-content-length-problem-solved/

"the WordPress Importer plugin is not compatible with remote servers that use HTTP compression."

For WordPress v4.6 and above, please use the following:

add_filter( 'http_request_args', function( $r, $url ) { $r['headers']['Accept-Encoding'] = 'identity'; return $r; }, 10, 2 );

**Comment by ocean90** [comment]
Can someone provide an example URL which is causing the issue?
