### ISSUE TITLE
Import via php function to 

### ISSUE THREAD

**Issue by Stevemoretz** [WordPress/wordpress-importer#80]
Hi I have this xml exporter which I would like to be Importer on my plugin activation,I can already enable this plugin if not enabled from php, but still need to import xml from php.Would you mind telling me how?

**Comment by dd32** [comment]
Hi @Stevemoretz - Apologies for the delay in response.

You may wish to look at how [wp-cli's wp import](https://github.com/wp-cli/import-command) process works, as that uses this plugin to perform the import.

Due to the age of this issue, I'm going to close it without much further explanation, if you still need help, please re-open it and let us know.
